---
races:
  - name: humans
    troops_number: 5
  - name: orcs
    troops_number: 5
land_types:
  - name: farmland
    conquest_points: 2
    color: '#FF8C00'
  - name: forest
    conquest_points: 2
    color: '#228B22'
  - name: hill
    conquest_points: 2
    color: '#FFD700'
  - name: mountain
    conquest_points: 3
    color: '#708090'
  - name: sea
    conquest_points: 2
    color: '#2266bb'
  - name: swamp
    conquest_points: 2
    color: '#333300'
